# Default values for aistemplate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: Always
  logService:
    repository: /fluent/fluent-bit:1.8.6
  envVersioning: false
  repository: /demo/hello-world

nameOverride: ""
fullnameOverride: ""
imageVersion: 0.0.1-SNAPSHOT
buildNumber: 1
logbackName: logback-spring

service:
  type: ClusterIP
  port: 3000
  targetport: 3000
  port2: 8081
  targetport2: 8081

istio:
  enabled: false
  namespace: enabled
  mesh: true

egress:
  enabled: false

probeUrl:
  enabled: false

traefik:
  enabled: false

svcCluster: false

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

redis:
  enabled: false

mock:
  enabled: false

masterNode:
  deployable: false

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
    ephemeral-storage: "5Gi"
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: "200Mi"

nodeSelector: {}

tolerations: []

affinity: {}

frontend:
  enabled: false

securityContext:
  capabilities:
    drop:
      - ALL
  runAsUser: 2000
  runAsGroup: 2000
  runAsNonRoot: true
  allowPrivilegeEscalation: false

release:
  stage: stable
  candidateEnabled: false

candidateList:
  dev: dev

java:
  security:
    downgrade: false

environment:
  dev:
    containerRegistry: acrlab1azassedev001.azurecr.io
    dnsName: az.intra.ais
    elasticHost: 10.144.9.104
    elasticUser: elastic
    elasticPassword: 
    elasticTLS: true
    elasticIndexPrefix: sub-entitlement-az-dev
    swagger: true
    httpEnabled: true
    tlsEnabled: true
    revisionHistoryLimit: "0"
    permanentCandidate: false
    clusterDomain: cluster.local
    prefixNamespace: true
    suffixNamespace: true
    gatewayName: dev-gateway
    nodeSelector:
      agentpool: agentpool
    kubernetesTCPAddr: entitlement-b4858d1d.hcp.southeastasia.azmk8s.io
    kubernetesPort: tcp://entitlement-b4858d1d.hcp.southeastasia.azmk8s.io:443
    kubernetesTCP: tcp://entitlement-b4858d1d.hcp.southeastasia.azmk8s.io:443
    kubernetesServiceHost: entitlement-b4858d1d.hcp.southeastasia.azmk8s.io
  sit:
    containerRegistry: acrentitlementazassedev001.azurecr.io
    dnsName: az.intra.ais
    elasticHost: 10.144.9.104
    elasticUser: elastic
    elasticPassword: 
    elasticTLS: true
    elasticIndexPrefix: sub-entitlement-az-dev
    swagger: true
    httpEnabled: true
    tlsEnabled: true
    revisionHistoryLimit: "0"
    permanentCandidate: false
    clusterDomain: cluster.local
    prefixNamespace: true
    suffixNamespace: true
    gatewayName: sit-gateway
    nodeSelector:
      agentpool: noodpool
    kubernetesTCPAddr: entitlement-b4858d1d.hcp.southeastasia.azmk8s.io
    kubernetesPort: tcp://entitlement-b4858d1d.hcp.southeastasia.azmk8s.io:443
    kubernetesTCP: tcp://entitlement-b4858d1d.hcp.southeastasia.azmk8s.io:443
    kubernetesServiceHost: entitlement-b4858d1d.hcp.southeastasia.azmk8s.io
  uat:
    containerRegistry: acrentitlementazassedev001.azurecr.io
    dnsName: az.intra.ais
    elasticHost: 10.144.9.40
    elasticUser: elastic
    elasticPassword: 
    elasticTLS: true
    elasticIndexPrefix: sub-entitlement-az-dev
    swagger: true
    httpEnabled: true
    tlsEnabled: true
    revisionHistoryLimit: "0"
    permanentCandidate: false
    clusterDomain: cluster.local
    prefixNamespace: true
    suffixNamespace: true
    gatewayName: uat-gateway
    nodeSelector:
      agentpool: noodpool
    kubernetesTCPAddr: entitlement-b4858d1d.hcp.southeastasia.azmk8s.io
    kubernetesPort: tcp://entitlement-b4858d1d.hcp.southeastasia.azmk8s.io:443
    kubernetesTCP: tcp://entitlement-b4858d1d.hcp.southeastasia.azmk8s.io:443
    kubernetesServiceHost: entitlement-b4858d1d.hcp.southeastasia.azmk8s.io
  prd:
    containerRegistry: acrentitlementazasseprd001.azurecr.io
    dnsName: az.intra.ais
    elasticHost: 10.145.9.36
    elasticUser: elastic
    elasticPassword: 
    elasticTLS: true
    elasticIndexPrefix: sub-entitlement-az-prd
    swagger: true
    httpEnabled: true
    tlsEnabled: true
    revisionHistoryLimit: "0"
    permanentCandidate: false
    clusterDomain: cluster.local
    prefixNamespace: false
    suffixNamespace: false
    gatewayName: prd-gateway
    nodeSelector:
      agentpool: noodpool
    kubernetesTCPAddr: entitlement-3e70cb65.hcp.southeastasia.azmk8s.io
    kubernetesPort: tcp://entitlement-3e70cb65.hcp.southeastasia.azmk8s.io:443
    kubernetesTCP: tcp://entitlement-3e70cb65.hcp.southeastasia.azmk8s.io:443
    kubernetesServiceHost: entitlement-3e70cb65.hcp.southeastasia.azmk8s.io
