---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
spec:
  selector:
    matchLabels:
      app: node-express-app
  template:
    metadata:
      labels:
        app: node-express-app
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: acrlab1azassedev001.azurecr.io/node-express-app:0.0.1-SNAPSHOT
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: node-express-app
spec:
  type: ClusterIP
  selector:
    app: node-express-app
  ports:
  - name: restapi
    port: 3000
    targetPort: 3000
---