projectDomainName: example

virutalService:
  - prefix:
      - "/nodex/"
    rewrite: "/"
    port: 3000
    host: node-express-app

externalServices:
  dev:
    - name: apim
      host: devoncloudapim.azure-api.net
      port: 443
      protocol: https
      mockAvailable: false
      retryOn: false
      perTryTimeout: "30s"
      timeout: "30s"
  sit:
  uat:
  prd:
